### PR TITLE
fix resending mail requests (#401)

### LINKED ISSUE #401: Keep sending reset requests
On the page "Mail Confirmation has been sent" if i press F5 keeps sending the email over and over.

### PR DESCRIPTION
**Pull request by davidcoutadeur**
Closes #401

### CODE REVIEW

File: htdocs/sendtoken.php [hunk 1]
```diff
@@ -48,7 +49,26 @@
...
+}
+
+if (! isset($_POST["mail"]) and ! isset($_REQUEST["login"])) {
+
+    $result = "emptysendtokenform";
+
+    # Generate formtoken
+    ini_set("session.use_cookies",0);
+    ini_set("session.use_only_cookies",1);
+    ini_set("session.use_strict_mode",0);
```
Comment (coudot) [inline htdocs/sendtoken.php:63]: We use `ini_set` in a lot of places in our code, and here in this page.

Maybe we should move them to index.php?

File: htdocs/sendtoken.php [hunk 2]
```diff
@@ -162,14 +182,42 @@
...
+    }
+    session_write_close();
 }
 
 #==============================================================================
 # Send token by mail
 #==============================================================================
 if ( !$result ) {
 
+
```
Comment (coudot) [inline htdocs/sendtoken.php:220]: Was it intentional to add this blank line?

File: htdocs/sendtoken.php (hunk 1 above)
Comment (davidcoutadeur) [reply htdocs/sendtoken.php:63]: Good point!

Maybe at some point we would need to have cookies sent for saving the session at client side. So, I am rather thinking to a dedicated function.

Also I am not quite satisfied by calling ini_set, whereas:
1. there are some warning in debug mode about misusage of ini_set function
2. it seems you can set those parameters in the session_start function (but my tests don't work for now)

File: htdocs/sendtoken.php (hunk 2 above)
Comment (davidcoutadeur) [reply htdocs/sendtoken.php:220]: No. I'll remove it

File: htdocs/sendtoken.php (hunk 1 above)
Comment (coudot) [reply htdocs/sendtoken.php:63]: Yes, using php session mechanism was an easy way to deal with tokens, but we may find a better solution. It will require a token backend on server side, which should be something easy to set up (files, in memory base, ...)

Comment (davidcoutadeur) [reply htdocs/sendtoken.php:63]: Unfortunately, I don't see a simple and clean way for doing this. Indeed, in `lib/captcha/InternalCaptcha.php` we also use ini_set, but in this context we need cookies.

I think the best would be to find and use a php lib for managing server sessions. I am opening a dedicated issue for that. Not sure we can fix this for next 1.7.0 release though.
